# 开发环境配置
quarkus:
  datasource:
    db-kind: h2
    username: sa
    password: ""
    jdbc:
      url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1

  # MyBatis configuration for development
  mybatis:
    mapper-locations: classpath*:mapper/*.xml
    configuration:
      map-underscore-to-camel-case: true
      log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl

  # Development logging
  log:
    level: INFO
    category:
      "com.example": DEBUG
      "com.example.mapper": DEBUG
    console:
      enable: true
      format: "%d{HH:mm:ss} %-5p [%c{2.}] (%t) %s%e%n"

  # CORS configuration for development
  http:
    cors:
      origins: "http://localhost:3000,http://localhost:8080"
      headers: "accept, authorization, content-type, x-requested-with"
      methods: "GET,PUT,POST,DELETE,OPTIONS"

  # JWT configuration
  smallrye-jwt:
    enabled: true

  # Development mode settings
  live-reload:
    instrumentation: true
