# メイン設定ファイル - プロファイル固有の設定は application-{profile}.yaml に記載

# JWT configuration
mp:
  jwt:
    verify:
      issuer: https://example.com
      publickey:
        location: META-INF/resources/publicKey.pem

smallrye:
  jwt:
    sign:
      key:
        location: META-INF/resources/privateKey.pem
  openapi:
    info:
      title: quarkus-template-app API
      version: 1.0.0-SNAPSHOT
      description: 企業レベルの認証権限管理システムのREST API
      contact:
        name: Development Team
        email: dev@example.com
    servers:
      - url: http://localhost:8080
        description: 開発環境
    security:
      - bearerAuth: []

# Quarkus configuration
quarkus:
  profile: dev

  # HTTP configuration
  http:
    port: 8081

  # Security configuration
  security:
    jaxrs:
      deny-unannotated-endpoints: false

  # OpenAPI configuration
  swagger-ui:
    always-include: true
    path: /q/swagger-ui

  # Metrics configuration
  micrometer:
    enabled: true
    export:
      prometheus:
        enabled: true

  # Health check configuration
  smallrye-health:
    ui:
      enable: true

  # Internationalization
  locales: ja,en,zh
  default-locale: ja
